---
name: Create release and deploy
on:
  workflow_dispatch:
jobs:
  release:
    name: Create release from main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Get current date and format to CalVer string
        run: echo "release_tag=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"
        id: release_tag_definition
      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.release_tag_definition.outputs.release_tag }}" \
              --repo="$GITHUIB_REPOSITORY" \
              --title="${{ steps.release_tag_definition.outputs.release_tag }}" \
              --generate-notes \
              --fail-on-no-commits
  call-deployment:
    name: Deployment
    needs: release
    permissions:
      contents: write
      pages: write
      id-token: write
      packages: write
    uses: ./.github/workflows/cd.yml
