---
name: Create release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Create release from main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Get current date and format to CalVer string
        run: echo "release_tag=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"
        id: release_tag_definition
      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.release_tag_definition.outputs.release_tag }}" \
              --repo="$GITHUIB_REPOSITORY" \
              --title="${{ steps.release_tag_definition.outputs.release_tag }}" \
              --generate-notes \
              --fail-on-no-commits
